
export default {

	USERS_RECEIVED: 		'USERS_RECEIVED',
	USER_CREATED: 			'USER_CREATED',
	USER_LOGGED_IN: 		'USER_LOGGED_IN',
	LOGOUT_USER:			'LOGOUT_USER',
	CURRENT_USER_RECEIVED: 	'CURRENT_USER_RECEIVED',

	ADD_BLOG_POST:			'ADD_BLOG_POST',
	ALL_BLOGS: 				'ALL_BLOGS',
	UPDATE_BLOG:			'UPDATE_BLOG',

	ALL_COMMENTS:			'ALL_COMMENTS'

}